### ISSUE TITLE
DatePicker and Sheet z-index

### ISSUE THREAD

**Issue by esseswann** [gravity-ui/date-components#11]
When calling DatePicker from Sheet on mobile the container is incorrectly z-positioned
![image](https://github.com/gravity-ui/date-components/assets/6066417/2509a329-242d-475f-ac2b-0ae95ffecb1c)

**Comment by ValeraS** [comment]
On mobile `DatePicker` uses native date picker. You need to use `MobileProvider` from `@gravity-ui/uikit` with `mobile=true`.
