### ISSUE TITLE
Calling state setter while rendering

### ISSUE THREAD

**Issue by lxndr** [gravity-ui/date-components#122]
Hello! I found

https://github.com/gravity-ui/date-components/blob/4cb03671bafa8102dc6514ca9e9474320163ee10/src/components/RangeDateField/hooks/useRangeDateFieldState.ts#L303

and

https://github.com/gravity-ui/date-components/blob/4cb03671bafa8102dc6514ca9e9474320163ee10/src/components/DateField/hooks/useDateFieldState.ts#L261

These are side effects and shouldn't exist. Please, take a look. This could have been affecting our app.

<img width="523" alt="Screenshot 2024-08-05 at 14 37 21" src="https://github.com/user-attachments/assets/382596dd-009c-4a45-94a7-e915e1d95f98">

**Comment by ValeraS** [comment]
Hello! Those setStates are valid. Here is a statement from React documentation:

> Calling the set function during rendering is only allowed from within the currently rendering component. React will discard its output and immediately attempt to render it again with the new state.

**Comment by ldrv565** [comment]
Hi. May I ask what is the point of using this pattern in these cases?

I have spent a little time to read about this, here is an explanation:

In most cases, you don’t need this:

- If the value you need can be computed entirely from the current props or other state, [remove that redundant state altogether.](https://react.dev/learn/choosing-the-state-structure#avoid-redundant-state) If you’re worried about recomputing too often, the [useMemo Hook](https://react.dev/reference/react/useMemo) can help.
- If you want to reset the entire component tree’s state, [pass a different key to your component.](https://react.dev/reference/react/useState#resetting-state-with-a-key)
- If you can, update all the relevant state in the event handlers.

**In the rare case that none of these apply, there is a pattern you can use to update state based on the values that have been rendered so far, by calling a set function while your component is rendering.**

The React documentation explains that this is a **rarely needed** pattern, only to store the previous value and **This pattern can be difficult to understand and is generally best avoided**. But this code does not do that.
What is the point?

https://react.dev/reference/react/useState#storing-information-from-previous-renders

**Comment by ldrv565** [comment]
Sorry, now I see that this case is fits to use case of this pattern

**Comment by ldrv565** [comment]
I think these hooks should be commented with a link above the function name, as this code is dangerous for the infinity loop and requires a lot of care when working with it.
 
https://react.dev/reference/react/useState#storing-information-from-previous-renders

**Comment by lxndr** [comment]
Ok, people. I don't seem o be able to reproduce it again. It cloud be one-off issue. It just looked weird - now we know it's alright. I'm closing this ticket.

**Comment by Arucard89** [comment]
Sorry for commenting closed issue.
May be we can use useEffect hook with necessary dependencies to update state here instead of [this](https://react.dev/reference/react/useState#storing-information-from-previous-renders)? it is possibly 
will be more readable?
