### ISSUE TITLE
[Bug] Wrong keyboard input

### ISSUE THREAD

**Issue by Ruminat** [gravity-ui/date-components#24]
## How to reproduce

- Go go https://preview.gravity-ui.com/date-components/?path=/story/components-datepicker--default
- Focus on the input
- Type `05` `28` `1998` on your keyboard

<img width="281" alt="image" src="https://github.com/gravity-ui/date-components/assets/18216279/cb63c219-54c4-4106-917c-81b2f8bb64d5">

## Expected

Correct date (`05.28.1998`)

<img width="289" alt="image" src="https://github.com/gravity-ui/date-components/assets/18216279/2cddb55a-10ff-4731-822d-f7142a4dc969">

## Actual result

Incorrect date (`05.01.1998`)

<img width="294" alt="image" src="https://github.com/gravity-ui/date-components/assets/18216279/928e5d2f-ab94-4684-b12a-fc3617742d58">

## Reproduced in browsers

Firefox, Yandex.Browser

**Comment by ValeraS** [comment]
fixed in #54
