### ISSUE TITLE
RelativeDatePicker allow input value less then minValue

### ISSUE THREAD

**Issue by EgorKluch** [gravity-ui/date-components#34]
I can't choose value less then minValue in Calendar, but can do it by input in text field.
<img width="273" alt="Screenshot 2024-01-18 at 19 19 27" src="https://github.com/gravity-ui/date-components/assets/2197074/5381f794-f78f-4f86-8aa5-2b2a97c1685d">

**Comment by EgorKluch** [comment]
There is no error message.

**Comment by ValeraS** [comment]
Cannot reproduce in storybook

![image](https://github.com/gravity-ui/date-components/assets/10867286/520e5470-4a10-47ac-8821-fe9128278c01)
