### ISSUE TITLE
Add"RangeValue" to the public interface

### ISSUE THREAD

**Issue by a1eksandrk** [gravity-ui/date-components#44]
It would be handy if added "RangeValue" to the public interface of the library. What do you think about it?
Right now I have to either import from dist or create my own type

<img width="804" alt="image" src="https://github.com/gravity-ui/date-components/assets/60098929/2707eea5-8d98-40d9-a41f-06f1990d34c1">

**Comment by ValeraS** [comment]
fixed in #54
