### ISSUE TITLE
RelativeRangeDatePicker: cannot write smth in input

### ISSUE THREAD

**Issue by saxumcordis** [gravity-ui/date-components#95]
Input has cursor, but it is always readonly

Calendar using is not always comfortable. I'd prefer using keyboard

**Comment by ValeraS** [comment]
RelativeRangeDatePicker can contain relative and absolute start and end dates in any combination. So input here is only for copying selected value. You still can select value in dialog box using a keyboard.

If you don't need relative dates, you can use RangeDatePicker, it supports typing in an input.

**Comment by saxumcordis** [comment]
> RelativeRangeDatePicker can contain relative and absolute start and end dates in any combination. So input here is only for copying selected value. You still can select value in dialog box using a keyboard.
> 
> If you don't need relative dates, you can use RangeDatePicker, it supports typing in an input.

I need both. Relative and input

**Comment by sareyu** [comment]
@saxumcordis @korvin89 @ValeraS guys, maybe we could set up a meeting and discuss possible solutions of this issue, as it is such complicated

**Comment by korvin89** [comment]
> @saxumcordis @korvin89 @ValeraS guys, maybe we could set up a meeting and discuss possible solutions of this issue, as it is such complicated

@sareyu  Sure, you can create one. But saxumcordis should be less toxic. Valera said his opinion and got only unsuitable reaction as answer

**Comment by saxumcordis** [comment]
A possible compromise is to remove the cursor from the input field (if it is read-only) and open the calendar when the input is pressed. This way, the user will not expect to be able to enter data when entering.

**Comment by saxumcordis** [comment]
https://github.com/gravity-ui/date-components/pull/104
